config/routes.rb
Rails.application.routes.draw do
  root 'countries#index'

  resources :countries
  # resources :countries, only: %i[index show update]

  devise_for :users
  devise_scope :user do
    delete  'logout', to: 'devise/sessions#destroy'
    get     'logout', to: 'devise/sessions#destroy'
  end
end

app/models/country.rb
# frozen_string_literal: true

class Country
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :capital, type: String
  field :region, type: String
  field :subregion, type: String
  field :flag, type: String

  validates :name, :flag, presence: true

  scope :recents, -> { order(created_at: :desc) }
end

app/models/user.rb
# frozen_string_literal: true

class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ''
  field :encrypted_password, type: String, default: ''

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :authenticate_user!
end

app/controllers/countries_controller.rb
# frozen_string_literal: true

class CountriesController < ApplicationController
  before_action :set_countries, only: :index
  before_action :set_country, only: %i[show edit update destroy]

  def index
    @pagy, @countries = pagy_array(Country.all.recents)
  end

  def show; end

  def new
    @country = Country.new
  end

  def edit; end

  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_country
    @country = Country.find(params[:id])
  end

  def country_params
    CountryPermittedParams.permitted_params_for(params[:country]).to_h
  end

  def set_countries
    return unless Country.all.empty?

    Requests::CountryService.new.execute
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/country_permitted_params.rb
# frozen_string_literal: true

class CountryPermittedParams
  PERMITTED_PARAMS = %i[name capital region subregion flag].freeze

  class << self
    def permitted_params_for(params)
      permitted_attributes = PERMITTED_PARAMS.dup

      params.permit(permitted_attributes).to_h
    end
  end
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>
      <ul>
        <% country.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :capital %>
    <%= form.text_field :capital %>
  </div>
  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>
  <div class="field">
    <%= form.label :subregion %>
    <%= form.text_field :subregion %>
  </div>
  <div class="field">
    <%= form.label :flag %>
    <%= form.text_field :flag %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/_nav.html.erb
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="far fa-window-restore"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <%= image_tag("favicon.png", alt: "Image placeholder") %>
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold"><%= current_user.email %></span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <div class="dropdown-divider"></div>
            <a href="" class="dropdown-item">
              <i class="ni ni-user-run"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/countries/_navbar.html.erb
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header  align-items-center">
      <a class="navbar-brand" href="javascript:void(0)">
        <%= image_tag("countries.png", alt: "...", class: "navbar-brand-img") %>
      </a>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" href="<%= countries_path %>">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Countries</span>
            </a>
          </li>
        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        <h6 class="navbar-heading p-0 text-muted">
          <span class="docs-normal">Coutries</span>
        </h6>
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">
          <li class="nav-item">
            <a class="nav-link active active-pro" href="<%= logout_path %>">
              <i class="ni ni-send text-dark"></i>
              <span class="nav-link-text">Logout</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/countries/edit.html.erb
<div class="main-content" id="panel">
  <!-- Topnav -->
  <%= render "nav" %>
  <!-- Header -->
  <div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Countries</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Countries</a></li>
                <li class="breadcrumb-item active" aria-current="page"><%= @country.name %></li>
              </ol>
            </nav>
          </div>
          <div class="col-lg-6 col-5 text-right">
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
    <div class="container-fluid mt--6">
    <div class="row">
      <div class="col-xl-12">
        <div class="card">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <%= render 'form', country: @country %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col text-right">
      <a href="<%= countries_path %>" class="btn btn-sm btn-primary">Back</a>
    </div>
  </div>
</div>

app/views/countries/index.html.erb
<!-- Main content -->
<div class="main-content" id="panel">
  <!-- Topnav -->
  <%= render "nav" %>
  <!-- Header -->
  <div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Countries</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Countries</a></li>
                <li class="breadcrumb-item active" aria-current="page">Index</li>
              </ol>
            </nav>
          </div>
          <div class="col-lg-6 col-5 text-right">
          </div>
        </div>
        <!-- Card stats -->
        <div class="row">
          <div class="col-xl-3 col-md-6">
            <div class="card card-stats">
              <!-- Card body -->
              <div class="card-body">
                <div class="row">
                  <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">Total Countries</h5>
                    <span class="h2 font-weight-bold mb-0"><%= @pagy.count %></span>
                  </div>
                  <div class="col-auto">
                    <div class="icon-shape bg-gradient-info text-white rounded-circle shadow">
                      <i class="ni ni-chart-bar-32"></i>
                    </div>
                  </div>
                </div>
                <p class="mt-3 mb-0 text-sm">
                  <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 100%</span>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col-xl-12">
        <div class="card">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <div class="col">
                <h3 class="mb-0">Countries</h3>
              </div>
              <div class="col text-right">
                <a href="<%= new_country_path %>" class="btn btn-sm btn-primary">New Country</a>
              </div>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table align-items-center table-flush">
              <thead class="thead-light">
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Capital</th>
                  <th scope="col">Region</th>
                  <th scope="col">Subregion</th>
                  <th scope="col">Flag</th>
                  <th scope="col">Options</th>
                </tr>
              </thead>
              <tbody>
                <% @countries.each do |country| %>
                  <tr>
                    <th scope="row"><%= country.name %></td>
                    <td><%= country.capital %></td>
                    <td><%= country.region %></td>
                    <td><%= country.subregion %></td>
                    <td>
                      <img src="<%= country.flag %>" alt="<%= country.name %>" height="30" width="30">
                    </td>
                    <td>
                      <%= link_to 'Show', country %>
                      <%= link_to 'Edit', edit_country_path(country) %>
                      <%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="pagy-nav">
          <%== pagy_bootstrap_combo_nav_js(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/countries/new.html.erb
<div class="main-content" id="panel">
  <!-- Topnav -->
  <%= render "nav" %>
  <!-- Header -->
  <div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Countries</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Countries</a></li>
                <li class="breadcrumb-item active" aria-current="page"><%= @country.name %></li>
              </ol>
            </nav>
          </div>
          <div class="col-lg-6 col-5 text-right">
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
    <div class="container-fluid mt--6">
    <div class="row">
      <div class="col-xl-12">
        <div class="card">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <%= render 'form', country: @country %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col text-right">
      <a href="<%= countries_path %>" class="btn btn-sm btn-primary">Back</a>
    </div>
  </div>
</div>

app/views/countries/show.html.erb
<div class="main-content" id="panel">
  <!-- Topnav -->
  <%= render "nav" %>
  <!-- Header -->
  <div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Countries</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Countries</a></li>
                <li class="breadcrumb-item active" aria-current="page"><%= @country.name %></li>
              </ol>
            </nav>
          </div>
          <div class="col-lg-6 col-5 text-right">
          </div>
        </div>
        <!-- Card stats -->
        <div class="row">
          <div class="col-xl-3 col-md-6">
            <div class="card card-stats">
              <!-- Card body -->
              <div class="card-body">
                <div class="row">
                  <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">Country Flag:</h5>
                    <div class="flag">
                      <img src="<%= @country.flag %>" alt="<%= @country.name %>" height="100" width="180">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
    <div class="container-fluid mt--6">
    <div class="row">
      <div class="col-xl-12">
        <div class="card">
          <div class="card-header border-0">
            <div class="row align-items-center">
              <div class="col">
                <h3 class="mb-0"><%= @country.name %></h3>
              </div>
              <div class="col text-right">
                <a href="<%= edit_country_path(@country) %>" class="btn btn-sm btn-primary">Edit Country</a>
              </div>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table align-items-center table-flush">
              <tbody class="thead-light">
                <tr>
                  <th>Name:</th>
                  <td><%= @country.name %></td>
                </tr>
                <tr>
                  <th>Capital:</th>
                  <td><%= @country.capital %></td>
                </tr>
                <tr>
                  <th>Region:</th>
                  <td><%= @country.region %></td>
                </tr>
                <tr>
                  <th>Subregion:</th>
                  <td><%= @country.subregion %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col text-right">
      <a href="<%= countries_path %>" class="btn btn-sm btn-primary">Back</a>
    </div>
  </div>

</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="py-5" id="footer-main">
  <div class="container">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-6">
        <div class="copyright text-center text-xl-left text-muted">
          &copy; 2021 <a href="https://alvaroalvarez.info" class="font-weight-bold ml-1" target="_blank">Alvaro Alvarez</a>
        </div>
      </div>
      <div class="col-xl-6">
        <ul class="nav nav-footer justify-content-center justify-content-xl-end">
          <li class="nav-item">
            <a href="https://alvaroalvarez.info" class="nav-link" target="_blank">Alvaro Alvarez</a>
          </li>
          <li class="nav-item">
            <a href="https://alvaroalvarez.info" class="nav-link" target="_blank">About Us</a>
          </li>
          <li class="nav-item">
            <a href="https://alvaroalvarez.info" class="nav-link" target="_blank">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">
      <%= image_tag("countries.png", alt: "") %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="<%= new_user_session_path %>" class="nav-link">
            <span class="nav-link-inner--text">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="<%= new_user_registration_path %>" class="nav-link">
            <span class="nav-link-inner--text">Register</span>
          </a>
        </li>
      </ul>
      <hr class="d-lg-none" />
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header  align-items-center">
      <a class="navbar-brand" href="javascript:void(0)">
        <%= image_tag("countries.png", alt: "...", class: "navbar-brand-img") %>
      </a>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" href="<%= countries_path %>">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Countries</span>
            </a>
          </li>
        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        <h6 class="navbar-heading p-0 text-muted">
          <span class="docs-normal">Coutries</span>
        </h6>
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">
          <li class="nav-item">
            <a class="nav-link active active-pro" href="<%= logout_path %>">
              <i class="ni ni-send text-dark"></i>
              <span class="nav-link-text">Logout</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Countries</title>

    <link rel="icon" href="<%= asset_path('favicon.png') %>" type="image/png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  </head>

  <body>
    <%= render "layouts/sidebar" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>User Layout</title>
    <link rel="icon" href="<%= asset_path('favicon.png') %>" type="image/png">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="bg-default">
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>